dougiteixeira/proxmoxve

- custom_components/proxmoxve/__init__.py
- custom_components/proxmoxve/button.py
Paritally fixes https://github.com/dougiteixeira/proxmoxve/issues/22
Please test the code, I've tried it but another round of testing would be great! btw, thanks for very nice code!
> Support for Node shutdown and reboot

- custom_components/proxmoxve/sensor.py
Fix VMs percentage free memory sensor
> Fix VMs percentage free memory sensor

- custom_components/proxmoxve/strings.json
- custom_components/proxmoxve/translations/en.json
Fix translation key for node selection field title.
> Fix translation key for node selection field title

- custom_components/proxmoxve/translations/en.json
> fixed typo

- custom_components/proxmoxve/__init__.py
Ignore warning InsecureRequestWarning: Unverified HTTPS log Logger: py.warnings
Fixes #92
> Ignore warning InsecureRequestWarning

- custom_components/proxmoxve/binary_sensor.py
- custom_components/proxmoxve/sensor.py
> Fixes unique id for multiple nodes

- custom_components/proxmoxve/config_flow.py
Fixes the error in the integration options config flow (#142).
> Fixes the error in the integration options config flow (#142).

- custom_components/proxmoxve/translations/de.json
> German translation

- custom_components/proxmoxve/translations/it.json
> Add Italian (it) translations

- custom_components/proxmoxve/binary_sensor.py
- custom_components/proxmoxve/coordinator.py
- custom_components/proxmoxve/models.py
- custom_components/proxmoxve/sensor.py
- custom_components/proxmoxve/strings.json
- custom_components/proxmoxve/translations/en.json
- custom_components/proxmoxve/translations/pt-BR.json
Adds sensors with information about update packages available on Proxmox.
The following permission is required for the feature to work:
* `["perm","/nodes/{node}",["Sys.Modify"]]`
> Adds sensors with information about update packages available

- custom_components/proxmoxve/translations/en.json
> Fix config flow labels

- README.md
- custom_components/proxmoxve/coordinator.py
- custom_components/proxmoxve/diagnostics.py
- custom_components/proxmoxve/manifest.json
- custom_components/proxmoxve/models.py
- custom_components/proxmoxve/sensor.py
- custom_components/proxmoxve/strings.json
- custom_components/proxmoxve/translations/en.json
- custom_components/proxmoxve/translations/pt-BR.json
Adds sensors for Temperature, Power cycles and Time on for physical disks
> Adds sensors for Temperature, Power cycles and Time on for physical disks

- README.md
- custom_components/proxmoxve/coordinator.py
- custom_components/proxmoxve/models.py
- custom_components/proxmoxve/sensor.py
- custom_components/proxmoxve/strings.json
- custom_components/proxmoxve/translations/en.json
- custom_components/proxmoxve/translations/pt-BR.json
Remove Power Hours sensor due to inconsistent update.
> Remove power hours info disks

- custom_components/proxmoxve/coordinator.py
- custom_components/proxmoxve/diagnostics.py
- custom_components/proxmoxve/manifest.json
Fix disk attributes when the API returns in text format.
Fixes #181
> Fix disk attributes when the API returns in text format

- custom_components/proxmoxve/__init__.py
- custom_components/proxmoxve/config_flow.py
- custom_components/proxmoxve/const.py
- custom_components/proxmoxve/diagnostics.py
- custom_components/proxmoxve/strings.json
- custom_components/proxmoxve/translations/en.json
- custom_components/proxmoxve/translations/pt-BR.json
Add option to disable physical disk information.
Fixes #186, #188 and #190.
> Add option to disable physical disk information

- custom_components/proxmoxve/sensor.py
- custom_components/proxmoxve/strings.json
- custom_components/proxmoxve/translations/de.json
- custom_components/proxmoxve/translations/en.json
- custom_components/proxmoxve/translations/it.json
- custom_components/proxmoxve/translations/pt-BR.json
Change the Uptime sensor description to Last boot
> Change the Uptime sensor description to Last boot

- custom_components/proxmoxve/coordinator.py
- custom_components/proxmoxve/models.py
- custom_components/proxmoxve/sensor.py
- custom_components/proxmoxve/strings.json
- custom_components/proxmoxve/translations/en.json
- custom_components/proxmoxve/translations/pt-BR.json
Adds the total number of VMs and Containers running on the node
> Adds the total number of VMs and Containers running on the node

- custom_components/proxmoxve/diagnostics.py
Add snapshots info in diagnostics
> Add snapshots info in diagnostics

- custom_components/proxmoxve/__init__.py
- custom_components/proxmoxve/api.py
- custom_components/proxmoxve/button.py
- custom_components/proxmoxve/config_flow.py
- custom_components/proxmoxve/const.py
- custom_components/proxmoxve/coordinator.py
- custom_components/proxmoxve/diagnostics.py
> Refactor API handling

- custom_components/proxmoxve/__init__.py
- custom_components/proxmoxve/api.py
- custom_components/proxmoxve/binary_sensor.py
- custom_components/proxmoxve/config_flow.py
- custom_components/proxmoxve/const.py
- custom_components/proxmoxve/coordinator.py
- custom_components/proxmoxve/diagnostics.py
- custom_components/proxmoxve/models.py
- custom_components/proxmoxve/sensor.py
> Ruff format

- custom_components/proxmoxve/__init__.py
- custom_components/proxmoxve/button.py
- custom_components/proxmoxve/sensor.py
> Fix import DeviceInfo

- custom_components/proxmoxve/config_flow.py
- custom_components/proxmoxve/strings.json
- custom_components/proxmoxve/translations/de.json
- custom_components/proxmoxve/translations/en.json
- custom_components/proxmoxve/translations/it.json
- custom_components/proxmoxve/translations/pt-BR.json
Fix async_step_change_expose exceptions
> Fix async_step_change_expose exceptions

- custom_components/proxmoxve/__init__.py
- custom_components/proxmoxve/coordinator.py
- custom_components/proxmoxve/diagnostics.py
> Fix pylint

- custom_components/proxmoxve/strings.json
> Fix strings ref

- custom_components/proxmoxve/const.py
> Fix impor Enum

- custom_components/proxmoxve/diagnostics.py
Separate get API data from Config Entry data
> Separate get API data from Config Entry data

- custom_components/proxmoxve/config_flow.py
Add async_process_selection_changes() in ProxmoxOptionsFlowHandler
> Add async_process_selection_changes() in ProxmoxOptionsFlowHandler

- custom_components/proxmoxve/__init__.py
- custom_components/proxmoxve/binary_sensor.py
- custom_components/proxmoxve/config_flow.py
- custom_components/proxmoxve/coordinator.py
- custom_components/proxmoxve/sensor.py
Fix coordinator name for Disks
> Fix coordinator name for Disks

- custom_components/proxmoxve/config_flow.py
> Fix remove devices Disks

- custom_components/proxmoxve/binary_sensor.py
- custom_components/proxmoxve/sensor.py
> Simplify async_setup_entry

- custom_components/proxmoxve/button.py
- custom_components/proxmoxve/sensor.py
> Fix mypy part 1

- custom_components/proxmoxve/__init__.py
- custom_components/proxmoxve/sensor.py
> Fix mypy part 2

- custom_components/proxmoxve/__init__.py
- custom_components/proxmoxve/config_flow.py
- custom_components/proxmoxve/coordinator.py
- custom_components/proxmoxve/diagnostics.py
- custom_components/proxmoxve/models.py
> Fix mypy part 3

- custom_components/proxmoxve/__init__.py
> Fix import YAML

- custom_components/proxmoxve/config_flow.py
> Fix mypy part 4

- custom_components/proxmoxve/binary_sensor.py
- custom_components/proxmoxve/sensor.py
Fix duplicate unique IDs for multiple node disks]
Fixes #203
> Fix duplicate unique IDs for multiple node disks

- custom_components/proxmoxve/binary_sensor.py
- custom_components/proxmoxve/button.py
- custom_components/proxmoxve/models.py
- custom_components/proxmoxve/sensor.py
Freeze integration entity descriptions
> Freeze entity descriptions

- custom_components/proxmoxve/diagnostics.py
> Fix diagnostics

- custom_components/proxmoxve/button.py
Fix commands QEMU and LXC entities
> Fix commands QEMU and LXC entities

- custom_components/proxmoxve/manifest.json
> Bump version to 3.3.0

- custom_components/proxmoxve/translations/pt-BR.json
Fix placeholders translations pt-BR
> Fix placeholders translations pt-BR

- custom_components/proxmoxve/config_flow.py
Use constante for integration title
> Use constante for integration title

- custom_components/proxmoxve/diagnostics.py
> Fix diagnostics formater

- custom_components/proxmoxve/const.py
Update version to remove YAML: 2025.1
> Update version to remove YAML

- custom_components/proxmoxve/coordinator.py
- custom_components/proxmoxve/models.py
- custom_components/proxmoxve/sensor.py
- custom_components/proxmoxve/strings.json
- custom_components/proxmoxve/translations/pt-BR.json
Add airflow temperature sensor for discs
Solve #233
> Add airflow temperature sensor for discs

- custom_components/proxmoxve/__init__.py
- custom_components/proxmoxve/binary_sensor.py
- custom_components/proxmoxve/button.py
- custom_components/proxmoxve/coordinator.py
- custom_components/proxmoxve/models.py
- custom_components/proxmoxve/sensor.py
> Refactor setup platforms

- custom_components/proxmoxve/api.py
> Change API timeout to 30s

- custom_components/proxmoxve/sensor.py
Change Power Cycles sensor status class to TOTAL_INCREASING
> Change Power Cycles sensor status class to TOTAL_INCREASING

- custom_components/proxmoxve/coordinator.py
Add function to get the SMART ID from the attribute name
> Add function to get the SMART ID from the attribute name

- custom_components/proxmoxve/coordinator.py
> Change exceptions for get_api

- custom_components/proxmoxve/coordinator.py
- custom_components/proxmoxve/models.py
- custom_components/proxmoxve/sensor.py
- custom_components/proxmoxve/strings.json
- custom_components/proxmoxve/translations/en.json
- custom_components/proxmoxve/translations/pt-BR.json
Add Life left, Power hours and Power loss sensors for the disks
> Add Life left, Power hours and Power loss sensors for the disks

- custom_components/proxmoxve/manifest.json
> Bump version to 3.4.0

- custom_components/proxmoxve/sensor.py
Changes the check to add entities to the sensor platform
> Changes the check to add entities to the sensor platform

- custom_components/proxmoxve/coordinator.py
Do not add the disk speed entity for SSD
> Do not add the disk speed entity for SSD

- custom_components/proxmoxve/translations/it.json
update IT translation to last version
> update IT translation

- custom_components/proxmoxve/coordinator.py
> Consider the case where the Power On Hours attribute is not a simple string

- custom_components/proxmoxve/coordinator.py
Do not add the disk speed entity for NVME and USB
> Do not add the disk speed entity for NVME and USB

- custom_components/proxmoxve/coordinator.py
The update does not fail when the disk does not have attributes
Fixes #257
> The update does not fail when the disk does not have attributes

- custom_components/proxmoxve/diagnostics.py
Fixes the diagnosis when there are no disk attributes
> Fixes the diagnosis when there are no disk attributes

- custom_components/proxmoxve/translations/it.json
Fix 3 warnings in HA for wrong placeholders in IT translation
> Fix it.json placeholders

- custom_components/proxmoxve/translations/de.json
Fix de translation placeholder
> Fix de translation placeholder

- custom_components/proxmoxve/__init__.py
- custom_components/proxmoxve/binary_sensor.py
- custom_components/proxmoxve/button.py
- custom_components/proxmoxve/config_flow.py
- custom_components/proxmoxve/coordinator.py
- custom_components/proxmoxve/diagnostics.py
- custom_components/proxmoxve/entity.py
- custom_components/proxmoxve/models.py
- custom_components/proxmoxve/sensor.py
> General RUFF fixes

- custom_components/proxmoxve/binary_sensor.py
Add OK on disk health
Fixes: #292
> Add OK on disk health

- custom_components/proxmoxve/coordinator.py
Fix the Power On Hours attribute of disks
> Fix the Power On Hours attribute of disks

- custom_components/proxmoxve/sensor.py
Prevents error due to UndefinedType in sensors
Fixes: #282
> Prevents error due to UndefinedType in sensors

- custom_components/proxmoxve/__init__.py
> Use model in the disk name

- custom_components/proxmoxve/__init__.py
- custom_components/proxmoxve/coordinator.py
- custom_components/proxmoxve/models.py
- custom_components/proxmoxve/sensor.py
> Add node in storage name

- custom_components/proxmoxve/coordinator.py
- custom_components/proxmoxve/models.py
- custom_components/proxmoxve/sensor.py
- custom_components/proxmoxve/strings.json
- custom_components/proxmoxve/translations/en.json
- custom_components/proxmoxve/translations/pt-BR.json
Add wearout sensor to SSD disks
#302
> Add wearout sensor to SSD disks

- custom_components/proxmoxve/sensor.py
Displays zero instead of unknown on sensors
#277
> Displays zero instead of unknown on sensors

- custom_components/proxmoxve/__init__.py
- custom_components/proxmoxve/api.py
- custom_components/proxmoxve/config_flow.py
- custom_components/proxmoxve/coordinator.py
- custom_components/proxmoxve/sensor.py
Fix deletion of repairs/issues
> Fix deletion of repairs/issues

- custom_components/proxmoxve/sensor.py
> Fix Wearout values for SSDs

- custom_components/proxmoxve/__init__.py
- custom_components/proxmoxve/api.py
- custom_components/proxmoxve/config_flow.py
- custom_components/proxmoxve/coordinator.py
> Fix repair handling

- custom_components/proxmoxve/__init__.py
Uses async_forward_entry_setups
> Uses async_forward_entry_setups

- custom_components/proxmoxve/manifest.json
> Change version to 3.4.4

- custom_components/proxmoxve/binary_sensor.py
- custom_components/proxmoxve/coordinator.py
> Fix update sensor availability available for packages

- README.md
- custom_components/proxmoxve/__init__.py
- custom_components/proxmoxve/api.py
- custom_components/proxmoxve/config_flow.py
- custom_components/proxmoxve/const.py
- custom_components/proxmoxve/strings.json
- custom_components/proxmoxve/translations/de.json
- custom_components/proxmoxve/translations/en.json
- custom_components/proxmoxve/translations/it.json
- custom_components/proxmoxve/translations/pt-BR.json
Workaround for https://github.com/dougiteixeira/proxmoxve/issues/338
> FEAT: Add token based authentication.

- custom_components/proxmoxve/translations/bg.json
Hello Team, 
Completed & contributing Bulgarian language translation support for the HA integration. Thank you.
> add BG lang UI support

- custom_components/proxmoxve/coordinator.py
> Fix warn status

- custom_components/proxmoxve/sensor.py
> Return zero for running containers and VMs

- custom_components/proxmoxve/config_flow.py
Reloads the integration after changing authentication information.
> Reloads the integration after changing authentication information

- custom_components/proxmoxve/config_flow.py
> Fix sets option flow config_entry explicitly

- custom_components/proxmoxve/config_flow.py
> Fix storage id

- custom_components/proxmoxve/translations/en.json
Small typo when configuring Node options.
> fix(typo): Update en.json

- custom_components/proxmoxve/sensor.py
> Set the disk temperature entities as a diagnosis

- custom_components/proxmoxve/__init__.py
> Fix via_device in device_info

- custom_components/proxmoxve/config_flow.py
- custom_components/proxmoxve/translations/en.json
It is now possible to change the host and port of the integration configuration through the reconfiguration flow.
Fixes #279
> Add reconfiguration flow

- custom_components/proxmoxve/__init__.py
- custom_components/proxmoxve/config_flow.py
- custom_components/proxmoxve/coordinator.py
> Use `wwn` as the main disk identifier
